apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume
spec:
  capacity:
   storage: 1Gi
  accessModes:
   - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set